# -*- coding: utf-8 -*-
"""01-03-26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vjxjG5JntlAn4_p1-w1h5LAQOzPKPCzi
"""

# variable length arguemnets
def add(*numbers): # to pass variable length values
  print(numbers)
add(1,2,3,4,5,6)

def add(*numbers):
  print(type(numbers))
add(1,2,3,4,5,6)

def add(*numbers):
  return sum(numbers)
add(1,2,3,45,67)

# **kwargs -> key worded arguements
def student_info(**details):
  for key,value in details.items():
    print(f"{key}:{value}")
student_info(name="keerthi",age=21,degree="B.E")

# lambda function a small anonymous function can be written using lambda .
add=lambda a,b:a*b
print(add(3,4))



power=lambda a,c:a**c
print(power(2,3))

double=lambda a:a*2
print(double(200))

students=[
    {"name":"keerthi","marks":10},
    {"name":"vijju","marks":15}
]
students.sort(key=lambda x:x["marks"],reverse=True)
print(students)

books=[
    {"name":"book1","price":100,"return_date":"10-2-25"},
    {"name":"book2","price":700,"return_date":"25-9-26"},
    {"name":"book3","price":70,"return_date":"10-8-25"},
    {"name":"book4","price":900,"return_date":"7-2-25"},
    {"name":"book5","price":100,"return_date":"10-3-25"},
    {"name":"book6","price":180,"return_date":"10-4-26"}
]
books.sort(key=lambda x:x["price"])
print(books)

books=[
    {"name":"book1","price":100,"return_date":"10-2-25"},
    {"name":"book2","price":700,"return_date":"25-9-26"},
    {"name":"book3","price":70,"return_date":"10-8-25"},
    {"name":"book4","price":900,"return_date":"7-2-25"},
    {"name":"book5","price":100,"return_date":"10-3-25"},
    {"name":"book6","price":180,"return_date":"10-4-26"}
]
books.sort(key=lambda x:x["price"])
for book in books:
    print(f"Name: {book['name']}, Price: {book['price']}, Return Date: {book['return_date']}")

# recursion -> a function calling itself .
def greet():
  print("hello")
  # greet()
greet()

def fact(n):
  if n==1:
    return 1
  return n*fact(n-1)
print(fact(5))

def outer_function(name):
  def inner_function(age):
    print(f"hello!,{name} ur age is:{age}")
  inner_function(21)
outer_function("keerthi")

def calculate(a,b):
  def add():
    print(a+b)
  def sub():
    print(a-b)
  def mul():
    print(a*b)
  mul()
  add()
  sub()
calculate(10,20)

# lambda function that multiplies 2 numbers
mul=lambda a,b:a*b
print(mul(2,7))

# recursive function to calculate sum of 1st n numbers
n_val = int(input("enter the number:"))

def recursive_sum_up_to_n(num):
  # Base case: if num is 0 or less, the sum is 0
  if num <= 0:
    return 0
  # Recursive case: add current num to the sum of numbers before it
  else:
    return num + recursive_sum_up_to_n(num - 1)

# Call the recursive function with the input number
result = recursive_sum_up_to_n(n_val)
print("The sum of the first", n_val, "numbers is:", result)

def avg(*num):
  total_sum = 0
  for number in num:
    total_sum += number

  # Check if there are any numbers to avoid division by zero
  if len(num) == 0:
    return 0 # Or you could raise an error for empty input

  average_value = total_sum / len(num) # Calculate average correctly
  return average_value

print(avg(1,5,6,8,9))