# -*- coding: utf-8 -*-
"""02-03-26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dSHQnP-0F7OYzi96ljI7akU5EThMHyqt
"""

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
    if n % 2==1 or 6<=n<=20:
        print("Weird")
    elif 2<=n<=5 or n>20:
        print("Not Weird")

if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(f"{a//b}\n{a/b}")

if __name__ == '__main__':
    n = int(input())
    i=0
    while i<n:
        print(i**2)
        i+=1

def is_leap(year):
    leap = False

    # Write your logic here
    if year % 4!= 0:
        leap = False
    else:
        if year % 100==0:
            if year % 400==0:
                leap = True
            else:
                leap = False
        else:
            leap = True
    return leap

year = int(input())
print(is_leap(year))