# -*- coding: utf-8 -*-
"""05-03-26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqyaviy4FL9VgTKTOscWiDyqseuLElpP
"""

records=[]
s=set()
for i in range(6):
    name=input()
    score=float(input())
    records.append([name,score])
    s.add(score)
sec_lowest_score=sorted(s)[1]
sec_lowest_name=[]

for name,score in records:
    if score==sec_lowest_score:
        sec_lowest_name.append(name)
for name in sorted(sec_lowest_name):
      print(name)