# -*- coding: utf-8 -*-
"""23-02-26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12wXWSxpu1lWdqxSJDmoN2INEKFbW_zFM
"""

import pandas as pd
df=pd.read_csv('/content/vgsales.csv')
print(df)

df=pd.DataFrame({
    'name':['a','b','c'],
    'regno':[1,2,3],
    'place':['mas','mys','hyd']
})
print(df)

df=pd.DataFrame({
    'name':['a','b','c'],
    'regno':[1,2,3],
    'place':['mas','mys','hyd'],
    'pno':[123,456,789]
})
print(df)

#SLICING
df['name'][:2]

#ACCESSING
df['regno']=[10,20,30]
df

df.loc[0,'name']='sss'
df

# boolean
a=True
s=pd.Series(a,name='Series')
print(s)
print(s.dtype)

a=1
s=pd.Series(a,name='Series')
print(s)
print(s.dtype)

a=0.7
s=pd.Series(a,name='Series')
print(s)
print(s.dtype)

a='keee'
s=pd.Series(a,name='Series')
print(s)
print(s.dtype)

a=[[1,2,3,4]]
s=pd.Series(a,name='Series')
print(s)
print(s.dtype)

a=[(1,2,3,4)]
s=pd.Series(a,name='Series')
print(s)
print(s.dtype)

a=1+2j
s=pd.Series(a,name='Series')
print(s)
print(s.dtype)

a=[{1,2,3,4}]
s=pd.Series(a,name='Series')
print(s)
print(s.dtype)

a=[{1:'a',2:'b'}]
s=pd.Series(a,name='Series')
print(s)
print(s.dtype)

# to get multiple records
import pandas as pd
df=pd.read_csv('/content/world_population.csv')
print(df)

# to get first 10 records
df.head(10) # head means initial records..

#HEAD-> first 5 records
df.head()

#tail
df.tail(10)# bottom 10 records

df.tail()# last 5 records

# all the details with the dataset type -.> info
df.info()

#describe-> takes all the information and performs some statisstical operation
df.describe()

+++++

df=pd.DataFrame({
    'name':['keerthi','chaitanya','sandhya','bhagya'],
    'age':[20,21,21,21],
    'marks':[87,89,88,89]

    })
print(df)

#a['name'][1:4]
df['name'][0:5:2]

df['marks'][2]

df['age']=55
print(df)

df.at[1,'marks']=100
print(df)

df.shape

df.dtypes
df.columns

a=pd.DataFrame({
    'Name':['keerthi','chaitanya','sandy','dhaniii','bhagya','keerthana','mytri','gaytri','neha'],
    'age':[20,21,22,23,22,21,22,23,23],
    'city':['chennai','kerala','bangalore','mangalore','mumbai','delhi','hubli','mumbai','delhi'],
    'marks':[90,98,90,89,90,98,98,98,89]
})
print(a)

# to clean the data
a.rename(columns={'name':'Name'})

a.drop_duplicates(inplace=True)
print(a)

a['city']=a['city'].str.title()
print(a)

a.isnull().sum() # to check for null value.
print(a)

mean_age=a['age'].mean()
a['age']=a['age'].filled(mean_age)
print(a)# if there is missing age it will assign vaule .

mean_marks=a['marks'].mean()
a['marks']=a['marks'].filled(mean_marks)
print(a)# if there is missing age it will assign vaule .