# -*- coding: utf-8 -*-
"""23-02-26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15sHMG86tm3KDTCQ0y-37VYSMDO0OHa_F

Reshape
convertion of 1d array to 2d or 3d
"""

import numpy as np  # 2-d array
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,])
b=a.reshape(4,3)
print(b)

import numpy as np  # 3-d convertion
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,])
b=a.reshape(2,2,3)
print(b)

"""Reshape (-1)-> convertion of 2d and 3d into 1d array (flatnening)"""

a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(-1)
print(b)

a=np.zeros(10)
print(a)

a=np.ones(10)
print(a)

a=np.identity(10)
print(a)

a=np.identity(3)
print(a)

# for indexing
a=np.array([1,2,3,4])
a[2]