# -*- coding: utf-8 -*-
"""26-02-26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hXDPhrOkkzLoGhpzNZ-A1-NFVk6z18G9
"""

s=input('string :' )
print(s.replace(" ",""))
print(len(s.replace(" ","")))

a=int(input("enter first number:"))
b=int(input("enter second  number:"))


print(a>10 and b>10)
print(a<5 or b<5)
print(not(a>5))

age=int(input("enter the age:"))

if age>=18:
  print("you arean adult")
else:
  print("you are not an adult")

s=input("s:")
print("a"in s)
print("pythons" not in s)

a,b=5,6
print(a & b)

print(a|b)

l=[1,"c",True,2,100]
l.append("end")
l.insert(2,"inserted_here")
print(l)
l.remove(l[2])
print(l)

l=[23,32,44,11]
l.sort()
print(l) #accsessending order
print(l[::-1])
l.reverse()
print(l)
print(l[::-1])

l.sort(reverse=True)
print(l)

#tuple
t=(1,2,3,4,5)
#t[0]=5 # tuples cant be modified
print(t[1:3])

t1=(1,2,3,4)
t2=(3,5,6)
print(t1+t2)

mf={"mango","butterfruit","apple"}
ff={"butterfruit","orange","strawberry"}
print(mf|ff)
print(mf&ff)
print(mf-ff)

mf={"mango","butterfruit","apple"}
mf.add("orange")
print(mf)
mf.remove("orange")
print(mf)
#mf.remove('banana')
mf.discard('banana') # if the value is not in the set it wont return the error
print(mf)

l=[1,2,34,56,789]
s=set(l)
print(s)
t=tuple(l)
print(t)
print(s,t)
s.add(10000)
print(s)