# -*- coding: utf-8 -*-
"""28-02-26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZdFamSaJWRiFQCS9I_XG-hPj7Xyng-lL
"""

#Functions
def greet():# defining a function
  print("hello!,Good Morning")
greet()# function call

def marriage(boy,girl):
  print(f"Boy is {boy}")
  print(f"Girl is {girl}")
  print(f"{boy} married {girl}")
marriage("chandan","sneha")# positional arguements
marriage(boy="heman",girl="saina")# keyword arguements

def tables(num):
  for i in range(1,11):
    print(f"{num}*{i}={num*i}")
tables(2)
tables(6)

# Default arguement
def marriage(boy,girl="Girl"):
  print(f"Boy is {boy}")
  print(f"Girl is {girl}")
  print(f"{boy} married {girl}")
marriage("chandan")

# Returning values from a function
def func(num):
  return int(str(num)*5)
a=100
c=a+func(1)
b=func(1)
c=a+b
print(c)

def func():
  x="chandan" # local variable
  print("hello world")
  print(y) # can be accessed
y="keerthi"# global variable
# print(x) # cannot acess x outside