# -*- coding: utf-8 -*-
"""oops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GOrzG1MkqOsKrJU7CEarinvNy_3yIdxg

Creating a class , defining parameters and objects and displaying them
"""

class Mobile:
  def __init__(self,brand,price):
    self.brand=brand
    self.price=price
  def display(self):
    print(f"{self.brand} costs {self.price}")
m1=Mobile("Samsung",20000)
m2=Mobile("apple",30000)
m1.display()
m2.display()

class student:
  def __init__(self,name,marks):
    self.name=name
    self.marks=marks

  def display_info(self):
    print(f"{self.name } has scored {self.marks} in the exam ")
s1=student("srinivas", 80)
s2=student("sri",90)
s1.display_info()
s2.display_info()

"""Constructor and self keywords"""

class movie:
  def __init__(self,title,rating ):
    self.title =title
    self.rating =rating

  def display_info(self):
    print(f"{self.title  } has  {self.rating }  ")
m1=movie("Toxic ", 4.5)
m2=movie("googly",5 )
m1.display_info()
m2.display_info()

class Employee:
  def __init__(self,name,designation,salary=30000):
    self.name=name
    self.designation=designation
    self.salary=salary

  def display_info(self):
    print(f"{self.name  } is  {self.designation  } and  has {self.salary} ")
e1=Employee("chandana","hr",50000)
e2=Employee("sri","developer")
e1.display_info()
e2.display_info()

"""4-pillars of oops"""

class bank_Acc:
  def __init__(self,acc_no,balance):
    self.__acc_no=acc_no
    self.__balance=balance
  def check_balance(self):
    print(f"your balance is {self.__balance}")
  def deposit(self,amount):
    self.__balance+=amount
    print(f"your balance is {self.__balance}")
  def withdraw(self,amount):
    if amount<=self.__balance:
      self.__balance-=amount
      print(f" withdraw is successful! your balance is {self.__balance}")
    else:
      print("insufficient balance")
A=bank_Acc(123456789,10000)
A.check_balance()
A.deposit(5000)
A.withdraw(15000)

class phone:
  def take_picture(self):
    print("picture taken ")
  def call_contact(self):
    print("calling the contact ")
p=phone()
p.take_picture()
p.call_contact()

#inheritance
class vehicle:
  def start(self):
    print("vehicle is starting")
class bike(vehicle):
  def __init__(self,name):
    self.name=name
  def ride(self):
    print("riding")
b=bike("re")
b.start()
b.ride()

# polymorphism

class shape:
  def area(self):
    print("area calculated ")
class circle(shape):
  def __init__(self,radius):
    self.radius=radius
  def area(self):
    print(f"area  of a circle is{(22/7)*self.radius*self.radius}")
class rectangle(shape):
  def __init__(self,l,b):
    self.l=l
    self.b=b
  def area(self):
    print(f"area  of a rectangle is{self.l*self.b}")
c=circle(5)
r=rectangle(3,4)
c.area()
r.area()

class bank_Acc:
  def __init__(self,balance):
    self.__balance=balance
  def get_balance(self):
    return self.__balance
  def set_balance(self,updated_balance):
    if updated_balance<0:
      print("invalid balance")
    self.__balance=updated_balance
A=bank_Acc(10000)
print(A.get_balance())
A.set_balance(20000)
A.get_balance()

class shape:
  def draw(self):
    print("drawing shape")
class circle(shape):
  def draw(self):
    super().draw()
    print("drawing circle")
c=circle()
c.draw()

from abc import ABC,abstractmethod
class Employee(ABC):
  @abstractmethod
  def calculate_salary(self):
    pass
class Manager(Employee):
  def calculate_salary(self):
    print("salary calculated for manager")
e1=Manager()
e1.calculate_salary()